import {
  ArrowLeftRight,
  Briefcase,
  Combine,
  FileImage,
  FileOutput,
  FileSpreadsheet,
  FileText,
  FileType,

  Gauge,
  Hash,
  Image,
  ImageDown,
  Info,
  LayoutGrid,
  ListOrdered,
  Lock,
  LockOpen,
  MessageSquareQuote,
  PenTool,
  Presentation,
  RotateCw,
  ScanText,
  Scissors,
  ShieldCheck,
  Sparkles,
  Stamp,
  Tags,
  Trash2,
  Wrench,
} from 'lucide-react';
import type { CategoryMeta, Tool } from '../types';

export const CATEGORIES: CategoryMeta[] = [
  { key: 'organization', label: 'PDF Organization', blurb: 'Combine, rearrange and compress documents.', icon: LayoutGrid },
  { key: 'editing', label: 'PDF Editing', blurb: 'Fine-tune, annotate and clean up pages.', icon: PenTool },
  { key: 'security', label: 'PDF Security', blurb: 'Lock and unlock your documents.', icon: ShieldCheck },
  { key: 'convert', label: 'PDF Conversion', blurb: 'Turn Office documents into clean, shareable PDFs.', icon: ArrowLeftRight },
  { key: 'image', label: 'Image to PDF', blurb: 'Turn images into polished PDF documents.', icon: FileImage },
  { key: 'office', label: 'PDF to Office', blurb: 'Export PDFs into editable Office formats.', icon: Briefcase },
  { key: 'utility', label: 'Utility Tools', blurb: 'Inspect and analyze your PDF files.', icon: Wrench },
  { key: 'ocr', label: 'OCR & Recognition', blurb: 'Turn scanned documents into searchable and editable files.', icon: ScanText },
  { key: 'ai', label: 'AI Document Intelligence', blurb: 'Summarize documents and ask questions grounded in facts.', icon: Sparkles },
];


export const TOOLS: Tool[] = [
  {
    slug: 'merge',
    name: 'Merge PDF',
    short: 'Merge PDFs',
    tagline: 'Combine multiple PDF files into one document.',
    description:
      'Drag in a stack of PDFs, or a selection of pages from them, and combine everything into a single organized document. Quality is preserved exactly; no recompression of your content.',
    category: 'organization',
    icon: Combine,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF files',
    multiple: true,
    output: 'pdf',
    endpoint: '/api/pdf/merge',
    fileField: 'pdfs',
    preview: 'first-pages',
    maxFiles: 20,
  },
  {
    slug: 'split',
    name: 'Split PDF',
    short: 'Split PDF',
    tagline: 'Pull a single page, ranges, or every page into separate files.',
    description:
      'Split a PDF exactly how you need it: extract one page, cut the document into named ranges, or export every page as its own PDF. Range splits arrive as a clean ZIP archive.',
    category: 'organization',
    icon: Scissors,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'zip',
    endpoint: '/api/pdf/split',
    fileField: 'pdf_file',
    preview: 'view',
    params: [
      {
        name: 'mode',
        label: 'Split mode',
        type: 'select',
        default: 'page',
        options: [
          { value: 'page', label: 'Extract a single page' },
          { value: 'ranges', label: 'Split into ranges' },
          { value: 'every', label: 'Split every page' },
        ],
      },
      {
        name: 'page',
        label: 'Page number',
        type: 'number',
        min: 1,
        default: 1,
        showWhen: { param: 'mode', value: 'page' },
      },
      {
        name: 'ranges',
        label: 'Ranges',
        type: 'text',
        placeholder: 'e.g. 1-3, 5, 7-9',
        description: 'Comma-separated ranges. Each range becomes its own PDF.',
        showWhen: { param: 'mode', value: 'ranges' },
      },
    ],
  },
  {
    slug: 'rotate',
    name: 'Rotate PDF',
    short: 'Rotate PDF',
    tagline: 'Rotate every page or just the ones you choose.',
    description:
      'Fix scanned documents or mixed-layout files by rotating pages 90, 180 or 270 degrees. Choose individual pages in the preview or rotate the whole document at once.',
    category: 'editing',
    icon: RotateCw,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/rotate',
    fileField: 'pdf_file',
    preview: 'select',
    params: [
      {
        name: 'angle',
        label: 'Direction',
        type: 'select',
        default: '90',
        options: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180° (upside down)' },
          { value: '270', label: '270° clockwise / 90° counter' },
        ],
      },
      {
        name: 'pages',
        label: 'Pages',
        type: 'text',
        auto: true,
        default: '',
      },
    ],
  },
  {
    slug: 'extract',
    name: 'Extract Pages',
    short: 'Extract pages',
    tagline: 'Pull selected pages into a new PDF.',
    description:
      'View thumbnails of every page and click to select the ones you want. The selected pages are collected into a brand-new PDF, leaving the original untouched.',
    category: 'editing',
    icon: FileOutput,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/extract',
    fileField: 'pdf_file',
    preview: 'select',
    params: [{ name: 'pages', label: 'Pages to extract', type: 'text', auto: true, default: '' }],
  },
  {
    slug: 'delete-pages',
    name: 'Delete Pages',
    short: 'Delete pages',
    tagline: 'Remove pages you do not need.',
    description:
      'Click pages in the preview to mark them for removal, then rebuild a clean PDF without them. You can never delete every page — at least one must remain.',
    category: 'editing',
    icon: Trash2,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/delete-pages',
    fileField: 'pdf_file',
    preview: 'select',
    params: [{ name: 'pages', label: 'Pages to delete', type: 'text', auto: true, default: '' }],
  },
  {
    slug: 'organize',
    name: 'Organize PDF',
    short: 'Organize pages',
    tagline: 'Drag and drop pages into the right order.',
    description:
      'A tactile page organizer. Drag thumbnails to reorder your document, and the new order is written straight back into the PDF.',
    category: 'organization',
    icon: ListOrdered,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/organize',
    fileField: 'pdf_file',
    preview: 'order',
    params: [{ name: 'order', label: 'Page order', type: 'text', auto: true, default: '' }],
  },
  {
    slug: 'compress',
    name: 'Compress PDF',
    short: 'Compress PDF',
    tagline: 'Shrink file size while protecting quality.',
    description:
      'Three honest compression levels. Low is fully lossless. Medium and high re-encode oversized images and keep page content sharp. The app tells you exactly how much space you saved.',
    category: 'organization',
    icon: Gauge,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/compress',
    fileField: 'pdf_file',
    preview: 'none',
    params: [
      {
        name: 'level',
        label: 'Compression level',
        type: 'select',
        default: 'medium',
        options: [
          { value: 'low', label: 'Low · lossless', description: 'No quality loss. Best for documents with heavy vector content.' },
          { value: 'medium', label: 'Medium · balanced', description: 'Re-encodes large images at high quality. Best for mixed documents.' },
          { value: 'high', label: 'High · smallest size', description: 'Aggressive image compression. Best for photo-heavy PDFs.' },
        ],
      },
    ],
  },
  {
    slug: 'watermark',
    name: 'Watermark PDF',
    short: 'Add text watermark',
    tagline: 'Brand your documents with translucent text.',
    description:
      'Add a subtle repeating watermark such as CONFIDENTIAL or DRAFT across every page, with control over size, opacity, color and placement.',
    category: 'editing',
    icon: Stamp,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/watermark',
    fileField: 'pdf_file',
    preview: 'view',
    params: [
      { name: 'text', label: 'Watermark text', type: 'text', required: true, placeholder: 'e.g. CONFIDENTIAL' },
      { name: 'font_size', label: 'Font size', type: 'range', min: 12, max: 160, step: 1, default: 48 },
      { name: 'opacity', label: 'Opacity', type: 'range', min: 0.05, max: 1, step: 0.05, default: 0.25 },
      { name: 'color', label: 'Color', type: 'color', default: '#9ca3af' },
      {
        name: 'position',
        label: 'Placement',
        type: 'select',
        default: 'diagonal',
        options: [
          { value: 'diagonal', label: 'Diagonal across page' },
          { value: 'center', label: 'Center' },
          { value: 'top-center', label: 'Top center' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-right', label: 'Top right' },
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
    ],
  },
  {
    slug: 'image-watermark',
    name: 'Image Watermark',
    short: 'Add logo watermark',
    tagline: 'Stamp your logo onto every page.',
    description:
      'Overlay a PNG or JPG logo onto your PDF at a corner or centered, sized to your liking with adjustable transparency.',
    category: 'editing',
    icon: Image,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/image-watermark',
    fileField: 'pdf_file',
    preview: 'view',
    params: [
      { name: 'logo', label: 'Logo image', type: 'logo', required: true },
      { name: 'size', label: 'Logo size', type: 'range', min: 24, max: 400, step: 4, default: 120 },
      { name: 'opacity', label: 'Opacity', type: 'range', min: 0.1, max: 1, step: 0.05, default: 0.8 },
      {
        name: 'position',
        label: 'Placement',
        type: 'select',
        default: 'bottom-right',
        options: [
          { value: 'top-left', label: 'Top left' },
          { value: 'top-center', label: 'Top center' },
          { value: 'top-right', label: 'Top right' },
          { value: 'center', label: 'Center' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
    ],
  },
  {
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    short: 'Add page numbers',
    tagline: 'Insert numbered labels onto each page.',
    description:
      'Add clean page numbers in any corner, starting from a number you choose — handy for reports submitted as part of a bigger set.',
    category: 'editing',
    icon: Hash,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/page-numbers',
    fileField: 'pdf_file',
    preview: 'view',
    params: [
      { name: 'start', label: 'First page number', type: 'number', min: 1, max: 9999, default: 1 },
      { name: 'font_size', label: 'Font size', type: 'range', min: 8, max: 40, step: 1, default: 14 },
      {
        name: 'position',
        label: 'Position',
        type: 'select',
        default: 'bottom-center',
        options: [
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-right', label: 'Bottom right' },
          { value: 'top-center', label: 'Top center' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-right', label: 'Top right' },
        ],
      },
    ],
  },
  {
    slug: 'protect',
    name: 'Protect PDF',
    short: 'Protect with password',
    tagline: 'Encrypt your document with AES-256.',
    description:
      'Lock a PDF with a user password so it cannot be opened without it, and choose what readers are allowed to print or copy. Encryption uses modern AES-256.',
    category: 'security',
    icon: Lock,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/protect',
    fileField: 'pdf_file',
    preview: 'view',
    params: [
      { name: 'user_password', label: 'User password', type: 'password', required: true, placeholder: 'Password to open the PDF' },
      { name: 'owner_password', label: 'Owner password (optional)', type: 'password', placeholder: 'Used to change permissions' },
      { name: 'allow_print', label: 'Allow printing', type: 'checkbox', default: true },
      { name: 'allow_copy', label: 'Allow copying text', type: 'checkbox', default: true },
      { name: 'allow_modify', label: 'Allow editing', type: 'checkbox', default: false },
    ],
  },
  {
    slug: 'unlock',
    name: 'Unlock PDF',
    short: 'Remove password',
    tagline: 'Unlock a PDF you know the password to.',
    description:
      'Remove password protection from a PDF when you have the password or the document only has a weak owner-level lock. Files you cannot legally access stay locked.',
    category: 'security',
    icon: LockOpen,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/unlock',
    fileField: 'pdf_file',
    preview: 'view',
    params: [
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Password (leave empty to try a weak lock)',
      },
    ],
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    short: 'Word → PDF',
    tagline: 'DOC/DOCX documents into clean PDFs.',
    description:
      'Convert Microsoft Word documents to PDF with exact layout fidelity using LibreOffice. Works for .docx and legacy .doc files.',
    category: 'convert',
    icon: FileText,
    kind: 'word',
    accept: '.doc,.docx',
    filesLabel: 'Word document',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/convert/word-to-pdf',
    fileField: 'file',
    preview: 'none',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    short: 'Excel → PDF',
    tagline: 'Spreadsheets into shareable PDFs.',
    description:
      'Turn .xlsx and .xls workbooks into PDFs. Print layouts from LibreOffice keep your tables readable and consistent.',
    category: 'convert',
    icon: FileSpreadsheet,
    kind: 'excel',
    accept: '.xls,.xlsx,.ods,.csv',
    filesLabel: 'Excel file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/convert/excel-to-pdf',
    fileField: 'file',
    preview: 'none',
  },
  {
    slug: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    short: 'PPT → PDF',
    tagline: 'Presentations into PDFs.',
    description:
      'Convert .pptx and .ppt decks to PDF while keeping slides crisp, so they render identically on any device.',
    category: 'convert',
    icon: Presentation,
    kind: 'ppt',
    accept: '.ppt,.pptx,.odp',
    filesLabel: 'PowerPoint file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/convert/ppt-to-pdf',
    fileField: 'file',
    preview: 'none',
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    short: 'PDF → Word',
    tagline: 'Extract text into a .docx document.',
    description:
      'Pulls the text layer out of a PDF and produces an editable Word document. Formatting, images and tables are not preserved — scanned PDFs need OCR.',
    category: 'office',
    icon: FileType,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'docx',
    endpoint: '/api/convert/pdf-to-word',
    fileField: 'pdf_file',
    preview: 'none',
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    short: 'JPG/PNG → PDF',
    tagline: 'Images into a single PDF at full quality.',
    description:
      'Combine JPG or PNG images into one PDF. Images are embedded at their native resolution with no lossy recompression.',
    category: 'image',
    icon: FileImage,
    kind: 'image',
    accept: 'image/jpeg,image/png,.jpg,.jpeg,.png',
    filesLabel: 'Images',
    multiple: true,
    output: 'pdf',
    endpoint: '/api/convert/jpg-to-pdf',
    fileField: 'images',
    preview: 'none',
    maxFiles: 30,
    params: [
      {
        name: 'page_size',
        label: 'Page size',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Match image size' },
          { value: 'a4', label: 'A4 sheet' },
        ],
      },
      {
        name: 'orientation',
        label: 'Orientation',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Auto' },
          { value: 'portrait', label: 'Portrait' },
          { value: 'landscape', label: 'Landscape' },
        ],
      },
    ],
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    short: 'PDF → JPG/PNG',
    tagline: 'Render every page as an image.',
    description:
      'Export each PDF page as a high-resolution JPG or PNG at the DPI you choose. Pages are delivered together in a ZIP archive.',
    category: 'utility',
    icon: ImageDown,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'zip',
    endpoint: '/api/convert/pdf-to-jpg',
    fileField: 'pdf_file',
    preview: 'none',
    params: [
      {
        name: 'dpi',
        label: 'Resolution',
        type: 'select',
        default: '150',
        options: [
          { value: '72', label: '72 DPI · screen' },
          { value: '150', label: '150 DPI · standard' },
          { value: '200', label: '200 DPI · print' },
          { value: '300', label: '300 DPI · high quality' },
        ],
      },
      {
        name: 'format',
        label: 'Format',
        type: 'select',
        default: 'jpg',
        options: [
          { value: 'jpg', label: 'JPG · smaller files' },
          { value: 'png', label: 'PNG · lossless' },
        ],
      },
    ],
  },
  {
    slug: 'pdf-info',
    name: 'PDF Inspector',
    short: 'PDF information',
    tagline: 'Understand what is inside a PDF.',
    description:
      'Inspect any PDF: page count, page dimensions, metadata, encryption state and whether it has a real text layer. No download needed.',
    category: 'utility',
    icon: Info,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'none',
    endpoint: '/api/pdf/info',
    fileField: 'pdf_file',
    preview: 'info',
    mode: 'info',
  },
  {
    slug: 'metadata',
    name: 'Edit Metadata',
    short: 'Edit metadata',
    tagline: 'Fix title, author and document properties.',
    description:
      'Read and update the document metadata that shows up in file properties — title, author, subject, keywords and creator — then download the updated PDF.',
    category: 'editing',
    icon: Tags,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/pdf/metadata',
    fileField: 'pdf_file',
    preview: 'metadata',
    mode: 'metadata',
    params: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'subject', label: 'Subject', type: 'text' },
      { name: 'keywords', label: 'Keywords', type: 'text' },
      { name: 'creator', label: 'Creator', type: 'text' },
    ],
  },
  {
    slug: 'ocr-to-pdf',
    name: 'OCR to PDF',
    short: 'OCR to PDF',
    tagline: 'Make scanned PDFs searchable with an invisible text layer.',
    description:
      'Transform scanned paper documents, contracts, receipts, and images into fully searchable PDFs. The original visual layout is preserved while adding an invisible, selectable text layer.',
    category: 'ocr',
    icon: ScanText,
    kind: 'pdf',
    accept: 'application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png',
    filesLabel: 'PDF or image',
    multiple: false,
    output: 'pdf',
    endpoint: '/api/ocr/pdf',
    fileField: 'file',
    preview: 'view',
    mode: 'ocr',
  },
  {
    slug: 'ocr-to-text',
    name: 'OCR to Text',
    short: 'OCR to Text',
    tagline: 'Extract readable text from scanned PDFs and images.',
    description:
      'Extract recognized text from scanned PDFs, photos, and receipts with clear page boundaries, interactive text preview, one-click copy, and .txt download.',
    category: 'ocr',
    icon: FileText,
    kind: 'pdf',
    accept: 'application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png',
    filesLabel: 'PDF or image',
    multiple: false,
    output: 'txt',
    endpoint: '/api/ocr/text',
    fileField: 'file',
    preview: 'view',
    mode: 'ocr',
  },
  {
    slug: 'ocr-to-word',
    name: 'OCR to Word',
    short: 'OCR to Word',
    tagline: 'Turn scanned documents into editable Word files.',
    description:
      'Convert scanned documents and image files into structured Microsoft Word (.docx) documents with paragraphs, headings, and clean page breaks.',
    category: 'ocr',
    icon: FileType,
    kind: 'pdf',
    accept: 'application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png',
    filesLabel: 'PDF or image',
    multiple: false,
    output: 'docx',
    endpoint: '/api/ocr/word',
    fileField: 'file',
    preview: 'view',
    mode: 'ocr',
  },
  {
    slug: 'pdf-summary',
    name: 'PDF Summary',
    short: 'Summarize PDF',
    tagline: 'Get a clear summary of the most important information in your PDF.',
    description:
      'Extract insights in seconds. Generates a grounded, factual summary with key takeaways, primary topics, and action items. Automatically handles scanned PDFs via OCR.',
    category: 'ai',
    icon: Sparkles,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF document',
    multiple: false,
    output: 'summary',
    endpoint: '/api/ai/summary',
    fileField: 'pdf_file',
    preview: 'view',
    mode: 'summary',
  },
  {
    slug: 'ask-pdf',
    name: 'Ask Questions with PDF',
    short: 'Ask PDF',
    tagline: 'Ask questions about your PDF and get answers grounded in its contents.',
    description:
      'Ask anything about your document and get factual, verified answers citing exact page numbers. If information is not in the document, it will honestly let you know.',
    category: 'ai',
    icon: MessageSquareQuote,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    filesLabel: 'PDF document',
    multiple: false,
    output: 'chat',
    endpoint: '/api/ai/ask',
    fileField: 'pdf_file',
    preview: 'view',
    mode: 'ask',
  },
];


export function getTool(slug: string): Tool | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

export function categoryOf(key: (typeof CATEGORIES)[number]['key']): CategoryMeta {
  return CATEGORIES.find((category) => category.key === key) ?? (CATEGORIES[0] as CategoryMeta);
}