import {
  Combine,
  Briefcase,
  FileImage,
  FileOutput,
  ImageDown,
  FileSpreadsheet,
  FileText,
  FileType,
  FileType2,
  Gauge,
  Hash,
  ImagePlus,
  Info,
  LayoutGrid,
  ListOrdered,
  Lock,
  LockOpen,
  MessageSquareQuote,
  PenLine,
  Presentation,
  RotateCw,
  ScanText,
  Scissors,
  ShieldCheck,
  Sparkles,
  Stamp,
  Tags,
  Trash2,
  SlidersHorizontal,
} from 'lucide-react';
import type { CategoryMeta, CategoryKey, Tool } from '../types';

/**
 * Single source of truth for every tool the backend actually implements.
 * `endpoint`, `fileField` and `params[].name` map 1:1 onto FastAPI form fields
 * — see backend/app/api/routes/{pdf,conversion}.py.
 */
export const CATEGORIES: CategoryMeta[] = [
  {
    key: 'organise',
    label: 'Organise PDF',
    blurb: 'Bring pages into order, trim bulk, and assemble documents.',
    icon: LayoutGrid,
  },
  {
    key: 'edit',
    label: 'Edit PDF',
    blurb: 'Rotate, extract, stamp and annotate existing pages.',
    icon: PenLine,
  },
  {
    key: 'convert-to',
    label: 'Convert to PDF',
    blurb: 'Turn Office files and images into clean, portable PDFs.',
    icon: FileText,
  },
  {
    key: 'convert-from',
    label: 'Convert from PDF',
    blurb: 'Export PDF content into editable or shareable formats.',
    icon: FileType2,
  },
  {
    key: 'security',
    label: 'PDF security',
    blurb: 'Encrypt documents, or remove a password you already own.',
    icon: ShieldCheck,
  },
  {
    key: 'utility',
    label: 'Utilities',
    blurb: 'Inspect a document before you commit to changing it.',
    icon: SlidersHorizontal,
  },
  {
    key: 'ocr',
    label: 'OCR & Recognition',
    blurb: 'Turn scanned documents into searchable and editable files.',
    icon: ScanText,
  },
  {
    key: 'ai',
    label: 'AI Document Intelligence',
    blurb: 'Summarize documents and ask questions grounded in facts.',
    icon: Sparkles,
  },
];


export const TOOLS: Tool[] = [
  {
    slug: 'merge',
    name: 'Merge PDF',
    short: 'Combine several PDFs into one',
    tagline: 'Combine multiple PDF files into one document.',
    description:
      'Drop in as many PDFs as you need and combine them into a single document. Page content is copied verbatim — nothing is recompressed or rasterised.',
    category: 'organise',
    icon: Combine,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF files',
    multiple: true,
    output: 'pdf',
    outputLabel: 'Single PDF',
    endpoint: '/api/pdf/merge',
    fileField: 'pdfs',
    preview: 'view',
    workspace: 'standard',
    maxFiles: 10,
    popular: true,
    action: 'Merge files',
    notes: ['Files are merged in the order shown in the list.', 'Documents are processed one after another, never mixed up.'],
  },
  {
    slug: 'split',
    name: 'Split PDF',
    short: 'Cut a PDF into separate documents',
    tagline: 'Pull out a single page, custom ranges, or every page.',
    description:
      'Split a document exactly how you need it: keep one page, cut it into named ranges, or export every page as its own PDF. Multi-file results arrive as a ZIP archive.',
    category: 'organise',
    icon: Scissors,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'zip',
    outputLabel: 'PDF or ZIP',
    endpoint: '/api/pdf/split',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'standard',
    action: 'Split PDF',
    params: [
      {
        name: 'mode',
        label: 'How should it split?',
        type: 'select',
        default: 'page',
        options: [
          { value: 'page', label: 'Extract one page', description: 'A single-page PDF is returned.' },
          { value: 'ranges', label: 'Split into ranges', description: 'Each range becomes its own PDF inside a ZIP.' },
          { value: 'every', label: 'Split every page', description: 'One PDF per page, delivered as a ZIP.' },
        ],
      },
      {
        name: 'page',
        label: 'Page number',
        type: 'number',
        min: 1,
        default: 1,
        showWhen: { param: 'mode', value: 'page' },
      },
      {
        name: 'ranges',
        label: 'Ranges',
        type: 'text',
        placeholder: '1-3, 5, 7-9',
        description: 'Comma separated, 1-based. Each range becomes its own file.',
        required: true,
        showWhen: { param: 'mode', value: 'ranges' },
      },
    ],
  },
  {
    slug: 'organise',
    name: 'Organise PDF',
    short: 'Reorder pages by dragging',
    tagline: 'Drag pages into the order you actually want.',
    description:
      'A tactile page organiser. Drag thumbnails to reorder the document — or nudge pages with the arrow controls when you prefer the keyboard — then write the new order back into the PDF.',
    category: 'organise',
    icon: ListOrdered,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Reordered PDF',
    endpoint: '/api/pdf/organize',
    fileField: 'pdf_file',
    preview: 'order',
    workspace: 'standard',
    popular: true,
    action: 'Save new order',
    params: [{ name: 'order', label: 'Page order', type: 'text', auto: true, default: '' }],
    notes: ['Every page must appear exactly once.', 'Rotate the PDF first if thumbnails look sideways.'],
  },
  {
    slug: 'compress',
    name: 'Compress PDF',
    short: 'Shrink file size, keep quality',
    tagline: 'Reduce file size with honest reporting.',
    description:
      'Three compression levels, described exactly as they behave. Low is fully lossless; medium and high re-encode oversized images while keeping text and vector art sharp. You always see the real bytes saved.',
    category: 'organise',
    icon: Gauge,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Smaller PDF',
    endpoint: '/api/pdf/compress',
    fileField: 'pdf_file',
    preview: 'none',
    workspace: 'standard',
    popular: true,
    action: 'Compress PDF',
    params: [
      {
        name: 'level',
        label: 'Compression level',
        type: 'select',
        default: 'medium',
        options: [
          { value: 'low', label: 'Low — lossless', description: 'Rebuilds the file structure without touching image data.' },
          { value: 'medium', label: 'Medium — balanced', description: 'Re-encodes large images at high quality. Good default.' },
          { value: 'high', label: 'High — smallest', description: 'Aggressive image compression for photo-heavy files.' },
        ],
      },
    ],
    notes: ['Savings depend entirely on the original file.', 'Already optimised PDFs may barely change.'],
  },
  {
    slug: 'rotate',
    name: 'Rotate PDF',
    short: 'Fix page orientation',
    tagline: 'Rotate every page, or only the ones you pick.',
    description:
      'Rescue scanned or mixed-layout documents by rotating pages 90°, 180° or 270°. Select individual pages in the preview, or leave the selection empty to rotate the whole document.',
    category: 'edit',
    icon: RotateCw,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Rotated PDF',
    endpoint: '/api/pdf/rotate',
    fileField: 'pdf_file',
    preview: 'select',
    workspace: 'standard',
    action: 'Rotate pages',
    params: [
      {
        name: 'angle',
        label: 'Rotation',
        type: 'select',
        default: '90',
        options: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180° — upside down' },
          { value: '270', label: '270° clockwise' },
        ],
      },
      { name: 'pages', label: 'Pages', type: 'text', auto: true, default: '' },
    ],
    notes: ['Preview thumbnails rotate to show the result.', 'No pages selected means every page rotates.'],
  },
  {
    slug: 'extract',
    name: 'Extract Pages',
    short: 'Keep only the pages you need',
    tagline: 'Collect chosen pages into a brand-new PDF.',
    description:
      'Click pages in the preview to build a new document from them. The original file is never modified, and the extracted pages keep their original order.',
    category: 'edit',
    icon: FileOutput,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Extracted PDF',
    endpoint: '/api/pdf/extract',
    fileField: 'pdf_file',
    preview: 'select',
    workspace: 'standard',
    action: 'Extract pages',
    params: [{ name: 'pages', label: 'Pages to extract', type: 'text', auto: true, default: '' }],
    notes: ['Select at least one page.', 'Pages are written in their original document order.'],
  },
  {
    slug: 'delete-pages',
    name: 'Delete Pages',
    short: 'Remove pages you do not need',
    tagline: 'Drop unwanted pages and rebuild the document.',
    description:
      'Mark pages for removal and rebuild a clean PDF without them. At least one page always remains, so you can never accidentally empty a document.',
    category: 'edit',
    icon: Trash2,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Trimmed PDF',
    endpoint: '/api/pdf/delete-pages',
    fileField: 'pdf_file',
    preview: 'select',
    workspace: 'standard',
    action: 'Delete pages',
    params: [{ name: 'pages', label: 'Pages to delete', type: 'text', auto: true, default: '' }],
    notes: ['At least one page must remain.', 'Marked pages are shown with a red overlay.'],
  },
  {
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    short: 'Number every page',
    tagline: 'Insert clean page numbers onto each page.',
    description:
      'Stamp page numbers in any corner, starting from any number. Useful when a report is going into a larger binder, or when pages simply need a reference.',
    category: 'edit',
    icon: Hash,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Numbered PDF',
    endpoint: '/api/pdf/page-numbers',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'standard',
    action: 'Add page numbers',
    params: [
      { name: 'start', label: 'First page number', type: 'number', min: 1, max: 9999, default: 1 },
      { name: 'font_size', label: 'Font size', type: 'range', min: 8, max: 40, step: 1, default: 14, unit: 'pt' },
      {
        name: 'position',
        label: 'Position',
        type: 'select',
        default: 'bottom-center',
        options: [
          { value: 'bottom-center', label: 'Bottom centre' },
          { value: 'bottom-right', label: 'Bottom right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'top-center', label: 'Top centre' },
          { value: 'top-right', label: 'Top right' },
          { value: 'top-left', label: 'Top left' },
        ],
      },
    ],
  },
  {
    slug: 'watermark',
    name: 'Text Watermark',
    short: 'Stamp text across pages',
    tagline: 'Brand documents with translucent text.',
    description:
      'Add a repeating watermark such as CONFIDENTIAL or DRAFT across every page, with control over wording, size, opacity, colour and placement.',
    category: 'edit',
    icon: Stamp,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Watermarked PDF',
    endpoint: '/api/pdf/watermark',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'standard',
    popular: true,
    action: 'Add watermark',
    params: [
      { name: 'text', label: 'Watermark text', type: 'text', required: true, placeholder: 'CONFIDENTIAL' },
      { name: 'font_size', label: 'Font size', type: 'range', min: 12, max: 160, step: 1, default: 48, unit: 'pt' },
      { name: 'opacity', label: 'Opacity', type: 'range', min: 0.05, max: 1, step: 0.05, default: 0.25 },
      { name: 'color', label: 'Colour', type: 'color', default: '#9CA3AF' },
      {
        name: 'position',
        label: 'Placement',
        type: 'select',
        default: 'diagonal',
        options: [
          { value: 'diagonal', label: 'Diagonal across the page' },
          { value: 'center', label: 'Centre' },
          { value: 'top-center', label: 'Top centre' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-right', label: 'Top right' },
          { value: 'bottom-center', label: 'Bottom centre' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
    ],
  },
  {
    slug: 'image-watermark',
    name: 'Image Watermark',
    short: 'Place a logo on every page',
    tagline: 'Stamp your logo onto every page.',
    description:
      'Overlay a PNG or JPG logo in any corner or in the centre of each page, sized in points and with adjustable transparency.',
    category: 'edit',
    icon: ImagePlus,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Watermarked PDF',
    endpoint: '/api/pdf/image-watermark',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'standard',
    action: 'Place logo',
    params: [
      { name: 'logo', label: 'Logo image', type: 'logo', required: true, description: 'PNG or JPG, up to 50 MB.' },
      { name: 'size', label: 'Logo width', type: 'range', min: 24, max: 400, step: 4, default: 120, unit: 'pt' },
      { name: 'opacity', label: 'Opacity', type: 'range', min: 0.1, max: 1, step: 0.05, default: 0.8 },
      {
        name: 'position',
        label: 'Placement',
        type: 'select',
        default: 'bottom-right',
        options: [
          { value: 'bottom-right', label: 'Bottom right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-center', label: 'Bottom centre' },
          { value: 'center', label: 'Centre' },
          { value: 'top-right', label: 'Top right' },
          { value: 'top-left', label: 'Top left' },
          { value: 'top-center', label: 'Top centre' },
        ],
      },
    ],
    notes: ['Transparent PNGs keep their transparency.'],
  },
  {
    slug: 'metadata',
    name: 'Edit Metadata',
    short: 'Fix title, author and keywords',
    tagline: 'Correct the document properties people see.',
    description:
      'Read the metadata already stored in a PDF, edit the values you want to change, and download the updated document. Existing fields you leave alone are preserved.',
    category: 'edit',
    icon: Tags,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Updated PDF',
    endpoint: '/api/pdf/metadata',
    fileField: 'pdf_file',
    preview: 'none',
    workspace: 'metadata',
    action: 'Save metadata',
    params: [
      { name: 'title', label: 'Title', type: 'text', placeholder: 'Document title' },
      { name: 'author', label: 'Author', type: 'text', placeholder: 'Author or team' },
      { name: 'subject', label: 'Subject', type: 'text', placeholder: 'Short description' },
      { name: 'keywords', label: 'Keywords', type: 'text', placeholder: 'comma, separated, tags' },
      { name: 'creator', label: 'Creator', type: 'text', placeholder: 'Application that authored the file' },
      { name: 'producer', label: 'Producer', type: 'text', placeholder: 'Application that produced the PDF' },
    ],
    notes: ['At least one field must be filled in.', 'Empty fields are removed from the document properties.'],
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    short: 'DOCX and DOC → PDF',
    tagline: 'Word documents, converted with layout intact.',
    description:
      'Convert Microsoft Word documents to PDF with the original layout preserved. Handles modern .docx files as well as legacy .doc.',
    category: 'convert-to',
    icon: FileText,
    kind: 'word',
    accept: '.doc,.docx',
    inputLabel: 'Word document',
    multiple: false,
    output: 'pdf',
    outputLabel: 'PDF',
    endpoint: '/api/convert/word-to-pdf',
    fileField: 'file',
    preview: 'none',
    workspace: 'standard',
    requires: 'office',
    action: 'Convert to PDF',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    short: 'XLSX and XLS → PDF',
    tagline: 'Spreadsheets, printed to PDF cleanly.',
    description:
      'Turn .xlsx and .xls workbooks into PDFs. The spreadsheet print layout is honoured, so tables stay readable and consistent.',
    category: 'convert-to',
    icon: FileSpreadsheet,
    kind: 'excel',
    accept: '.xls,.xlsx',
    inputLabel: 'Excel workbook',
    multiple: false,
    output: 'pdf',
    outputLabel: 'PDF',
    endpoint: '/api/convert/excel-to-pdf',
    fileField: 'file',
    preview: 'none',
    workspace: 'standard',
    requires: 'office',
    action: 'Convert to PDF',
  },
  {
    slug: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    short: 'PPTX and PPT → PDF',
    tagline: 'Slides that render the same everywhere.',
    description:
      'Convert .pptx and .ppt presentations into PDFs so slides look identical on any device, with one slide per page.',
    category: 'convert-to',
    icon: Presentation,
    kind: 'ppt',
    accept: '.ppt,.pptx',
    inputLabel: 'PowerPoint file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'PDF',
    endpoint: '/api/convert/ppt-to-pdf',
    fileField: 'file',
    preview: 'none',
    workspace: 'standard',
    requires: 'office',
    action: 'Convert to PDF',
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    short: 'Images → one PDF',
    tagline: 'Combine JPG or PNG images into a PDF.',
    description:
      'Assemble images into one PDF in the order you arrange them. Images are embedded at their native resolution — no lossy recompression.',
    category: 'convert-to',
    icon: FileImage,
    kind: 'image',
    accept: 'image/jpeg,image/png,.jpg,.jpeg,.png',
    inputLabel: 'JPG or PNG images',
    multiple: true,
    output: 'pdf',
    outputLabel: 'PDF',
    endpoint: '/api/convert/jpg-to-pdf',
    fileField: 'images',
    preview: 'none',
    workspace: 'standard',
    maxFiles: 30,
    popular: true,
    action: 'Create PDF',
    params: [
      {
        name: 'page_size',
        label: 'Page size',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Match each image' },
          { value: 'a4', label: 'A4 sheet' },
        ],
      },
      {
        name: 'orientation',
        label: 'Orientation',
        type: 'select',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Automatic' },
          { value: 'portrait', label: 'Portrait' },
          { value: 'landscape', label: 'Landscape' },
        ],
        showWhen: { param: 'page_size', value: 'a4' },
      },
    ],
    notes: ['Images keep their original resolution.', 'Drag or reorder the list to change page order.'],
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    short: 'PDF → editable DOCX',
    tagline: 'Extract PDF text into an editable document.',
    description:
      'Pulls the text layer out of a PDF and produces an editable Word document, with running headers removed and paragraphs rejoined. Layout, images and tables are not reproduced.',
    category: 'convert-from',
    icon: Briefcase,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'docx',
    outputLabel: 'Word document',
    endpoint: '/api/convert/pdf-to-word',
    fileField: 'pdf_file',
    preview: 'none',
    workspace: 'standard',
    action: 'Convert to Word',
    notes: [
      'Text only — formatting, images and tables are not preserved.',
      'Scanned documents need OCR first, because they contain no text layer.',
    ],
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    short: 'PDF → JPG or PNG images',
    tagline: 'Render every page as an image.',
    description:
      'Export each page as a high-resolution JPG or PNG at the resolution you choose. All pages are delivered together in a ZIP archive.',
    category: 'convert-from',
    icon: ImageDown,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'zip',
    outputLabel: 'ZIP of images',
    endpoint: '/api/convert/pdf-to-jpg',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'standard',
    action: 'Export images',
    params: [
      {
        name: 'dpi',
        label: 'Resolution',
        type: 'select',
        default: '150',
        options: [
          { value: '72', label: '72 DPI — web preview' },
          { value: '150', label: '150 DPI — standard' },
          { value: '200', label: '200 DPI — print' },
          { value: '300', label: '300 DPI — high quality' },
        ],
      },
      {
        name: 'format',
        label: 'Image format',
        type: 'select',
        default: 'jpg',
        options: [
          { value: 'jpg', label: 'JPG — smaller files' },
          { value: 'png', label: 'PNG — lossless' },
        ],
      },
    ],
    notes: ['Higher DPI means larger images and longer processing.'],
  },
  {
    slug: 'protect',
    name: 'Protect PDF',
    short: 'Encrypt with a password',
    tagline: 'Lock a document behind AES-256 encryption.',
    description:
      'Set a password needed to open the PDF, and decide what readers may print, copy or edit. Files are encrypted with modern AES-256.',
    category: 'security',
    icon: Lock,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Encrypted PDF',
    endpoint: '/api/pdf/protect',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'standard',
    action: 'Protect PDF',
    params: [
      { name: 'user_password', label: 'Open password', type: 'password', required: true, placeholder: 'Required to open the file' },
      { name: 'owner_password', label: 'Owner password', type: 'password', placeholder: 'Optional — needed to change permissions' },
      { name: 'allow_print', label: 'Allow printing', type: 'checkbox', default: true },
      { name: 'allow_copy', label: 'Allow copying text', type: 'checkbox', default: true },
      { name: 'allow_modify', label: 'Allow editing', type: 'checkbox', default: false },
    ],
    notes: ['Passwords are used once and never stored.', 'Keep the password safe — it cannot be recovered from the output.'],
  },
  {
    slug: 'unlock',
    name: 'Unlock PDF',
    short: 'Remove a password you know',
    tagline: 'Remove protection from a PDF you own.',
    description:
      'Remove password protection when you know the password, or when the document only carries a weak owner-level restriction. Files you cannot legally access stay locked.',
    category: 'security',
    icon: LockOpen,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Unprotected PDF',
    endpoint: '/api/pdf/unlock',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'standard',
    action: 'Unlock PDF',
    params: [
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Leave empty to try an owner-only lock',
        description: 'Wrong passwords are rejected — nothing is bypassed.',
      },
    ],
  },
  {
    slug: 'pdf-info',
    name: 'Inspect PDF',
    short: 'Read structure and metadata',
    tagline: 'Understand what is inside a PDF.',
    description:
      'Inspect page count, page dimensions, document metadata, encryption state and whether the file carries a real text layer. Nothing is modified and nothing is downloaded.',
    category: 'utility',
    icon: Info,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF file',
    multiple: false,
    output: 'none',
    outputLabel: 'Report only',
    endpoint: '/api/pdf/info',
    fileField: 'pdf_file',
    preview: 'none',
    workspace: 'inspector',
    action: 'Inspect file',
    popular: true,
  },
  {
    slug: 'ocr-to-pdf',
    name: 'OCR to PDF',
    short: 'OCR to PDF',
    tagline: 'Make scanned PDFs searchable with an invisible text layer.',
    description:
      'Transform scanned paper documents, contracts, receipts, and images into fully searchable PDFs. The original visual layout is preserved while adding an invisible, selectable text layer.',
    category: 'ocr',
    icon: ScanText,
    kind: 'pdf',
    accept: 'application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png',
    inputLabel: 'PDF or image',
    multiple: false,
    output: 'pdf',
    outputLabel: 'Searchable PDF',
    endpoint: '/api/ocr/pdf',
    fileField: 'file',
    preview: 'view',
    workspace: 'ocr',
    action: 'Run OCR to PDF',
  },
  {
    slug: 'ocr-to-text',
    name: 'OCR to Text',
    short: 'OCR to Text',
    tagline: 'Extract readable text from scanned PDFs and images.',
    description:
      'Extract recognized text from scanned PDFs, photos, and receipts with clear page boundaries, interactive text preview, one-click copy, and .txt download.',
    category: 'ocr',
    icon: FileText,
    kind: 'pdf',
    accept: 'application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png',
    inputLabel: 'PDF or image',
    multiple: false,
    output: 'txt',
    outputLabel: 'Text file',
    endpoint: '/api/ocr/text',
    fileField: 'file',
    preview: 'view',
    workspace: 'ocr',
    action: 'Extract text',
  },
  {
    slug: 'ocr-to-word',
    name: 'OCR to Word',
    short: 'OCR to Word',
    tagline: 'Turn scanned documents into editable Word files.',
    description:
      'Convert scanned documents and image files into structured Microsoft Word (.docx) documents with paragraphs, headings, and clean page breaks.',
    category: 'ocr',
    icon: FileType,
    kind: 'pdf',
    accept: 'application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png',
    inputLabel: 'PDF or image',
    multiple: false,
    output: 'docx',
    outputLabel: 'Word document',
    endpoint: '/api/ocr/word',
    fileField: 'file',
    preview: 'view',
    workspace: 'ocr',
    action: 'Convert to Word',
  },
  {
    slug: 'pdf-summary',
    name: 'PDF Summary',
    short: 'Summarize PDF',
    tagline: 'Get a clear summary of the most important information in your PDF.',
    description:
      'Extract insights in seconds. Generates a grounded, factual summary with key takeaways, primary topics, and action items. Automatically handles scanned PDFs via OCR.',
    category: 'ai',
    icon: Sparkles,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF document',
    multiple: false,
    output: 'summary',
    outputLabel: 'Summary report',
    endpoint: '/api/ai/summary',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'summary',
    action: 'Generate summary',
  },
  {
    slug: 'ask-pdf',
    name: 'Ask Questions with PDF',
    short: 'Ask PDF',
    tagline: 'Ask questions about your PDF and get answers grounded in its contents.',
    description:
      'Ask anything about your document and get factual, verified answers citing exact page numbers. If information is not in the document, it will honestly let you know.',
    category: 'ai',
    icon: MessageSquareQuote,
    kind: 'pdf',
    accept: 'application/pdf,.pdf',
    inputLabel: 'PDF document',
    multiple: false,
    output: 'chat',
    outputLabel: 'Interactive Q&A',
    endpoint: '/api/ai/ask',
    fileField: 'pdf_file',
    preview: 'view',
    workspace: 'ask',
    action: 'Ask PDF',
  },
];

export const TOOL_MAP: Record<string, Tool> = Object.fromEntries(TOOLS.map((tool) => [tool.slug, tool]));

export function getTool(slug: string | undefined): Tool | undefined {
  return slug ? TOOL_MAP[slug] : undefined;
}

export function toolsInCategory(key: CategoryKey): Tool[] {
  return TOOLS.filter((tool) => tool.category === key);
}

export function categoryOf(key: CategoryKey): CategoryMeta {
  return CATEGORIES.find((category) => category.key === key) ?? (CATEGORIES[0] as CategoryMeta);
}

export const POPULAR_TOOLS: Tool[] = TOOLS.filter((tool) => tool.popular);

/** Related tools shown at the end of a workspace: same category, nearest first. */
export function relatedTools(tool: Tool, limit = 3): Tool[] {
  const sameCategory = TOOLS.filter((item) => item.slug !== tool.slug && item.category === tool.category);
  const others = TOOLS.filter((item) => item.slug !== tool.slug && item.category !== tool.category);
  return [...sameCategory, ...others].slice(0, limit);
}

export function toolMatchesQuery(tool: Tool, query: string): boolean {
  const needle = query.trim().toLowerCase();
  if (!needle) return true;
  const category = categoryOf(tool.category);
  const haystack = [tool.name, tool.short, tool.tagline, tool.description, tool.inputLabel, tool.outputLabel, category.label]
    .join(' ')
    .toLowerCase();
  return needle.split(/\s+/).every((term) => haystack.includes(term));
}
